### PR TITLE
Blog app - integration specs for views and fix n+1 problems

### PR DESCRIPTION
**Pull request by ogagaoghene**
# Blog app - integration specs for views and fix n+1 problems

## Description
In this project, I will add Integration specs and fix n+1 issues as they occur

I contacted support about this Rspec GitHub action failure remotely but not locally. They asked that I provide images for successful test running locally. 

Find them below
image
image
image

The tests are run as follows:

rspec spac/users_spec.rb
rspec spec/posts_spec.rb

### CODE REVIEW

**Review by danielufeli — CHANGES_REQUESTED** [review]
Hi @ogagaogbene, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has linter errors.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by ogagaoghene** [comment]
@danielufeli  I explained everything to you. This has nothing to do with the logic of the application or linting locally. I have been on call with those senior reviewers and they still could not fix it. They suggested I make the case. What is most important is that the test cases are working fine. All configurations are okay in the local rails_helper.rb, spec_helper.rb file and config/database.yml files. Why should this prevent me from progressing? It does not make sense. We have exhausted all options. I once had similar issue and I was considered and I made progress. Please kindly be discretional. That's how it works

**Comment by ogagaoghene** [comment]
@danielufeli I have been on this since 2am and there is still no head way. It is frustrating. If it does not work now,when will it work.? Please allow me to make progress I humbly ask. If you can help, we can arrange for a zoom meeting. I have only some few hours before midnight and I also have some other tasks to complete with my coding partner

**Comment by ogagaoghene** [comment]
@danielufeli Please be flexible. The idea of learning is the logic and implementation of the solution to the problem. This is causing me a whole lot of emotional pain already. I have removed database_cleaner, add gems remove gems bundle install etc

**Comment by danielufeli** [comment]
Re submit

**Comment by ogagaoghene** [comment]
@danielufeli Thank you sir. I sincerely appreciate you greatly

**Comment by ogagaoghene** [comment]
@danielufeli Thank you my Naija brother

**Review by EricMbouwe — APPROVED** [review]
Hi @ogagaoghene, 

Your project is complete! ⚡🔥  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 🎉🔥
- Test coverage ✔
- Passed test ✔

## Optional suggestions ☂

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ogagaoghene** [comment]
Thanks for your professional review. I appreciate your effort

**Pull request merged**
