### PR TITLE
Blog app: add API endpoints

### PR DESCRIPTION
**Pull request by ogagaoghene**
# Blog app: add API endpoints

## Description
Add Basic API endpoints to the BlogApp

### CODE REVIEW

**Review by Whoistolu — APPROVED** [review]
### Hi Team,
@ogagaoghene , @Estherstarr , @looh16 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

### Highlight
✔️ Descriptive PR
✔️ Meaningful Commit Messages

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by looh16** [comment]
Thanks

**Comment by ogagaoghene** [comment]
@Whoistolu Many thanks to you for your professional code review. I am eternally grateful to you

**Comment by Whoistolu** [comment]
You’re welcome @ogagaoghene !
Happy coding 👏👏👏

**Pull request merged**
